title = "DeputyDev configuration"

[app]
name = ""
description = ""
language = ""
framework = ""
owner = ""

[code_review_agent]
enable = true                       # Set to true to enable the code review agent, false to disable
is_override = true                 # Set to true if this configuration can be overridden by repo level configuration
model = "claude_3.5_sonnet"         # Specifying which model to use for code reviews
exclusions = [
    "Pipfile.lock",
    "bitbucket-pipelines.yml",
    "package-lock.json",
    "poetry.lock",
    "pyproject.toml",
    "README.md",
    "chromedriver",
    "local_execute.sh",
    "local_build.sh",
]
inclusions = []

# Objective have no use for pre-defined agents, Added this to make agents simmillar and extensible.
[code_review_agent.agents.security]
agent_id = "c62142f5-3992-476d-9131-bf85e1beffb7"
display_name = "Security"
weight = 5
enable = true
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.9              # Threshold of confidence_score for a comment to qualify to be made on PR
objective = "Responsibility of this agent is checking security issues"
is_custom_agent = false
is_corrective_code_enabled = false

[code_review_agent.agents.code_communication]
agent_id = "36b9b529-3ad4-4ddf-9a12-8537ea9765a8"
display_name = "Documentation"
weight = 1
enable = true
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.98
objective = "Responsibility of this agent is checking code_communication issues"
is_custom_agent = false
is_corrective_code_enabled = false

[code_review_agent.agents.performance_optimisation]
agent_id = "5932a405-96cb-4508-bfd4-443397583f95"
display_name = "Performance Optimization"
weight = 3
enable = true
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.9
objective = "Responsibility of this agent is checking performance issues"
is_custom_agent = false
is_corrective_code_enabled = false

[code_review_agent.agents.code_maintainability]
agent_id = "ccfe1b06-f5f2-42b1-a209-4d560edbd5f4"
display_name = "Code Maintainabiltiy"
weight = 3
enable = true
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.9
objective = "Responsibility of this agent is checking code maintainability issues"
is_custom_agent = false
is_corrective_code_enabled = false

[code_review_agent.agents.error]
agent_id = "4a3f593d-73cd-41d6-85a0-dc96c17ce9bb"
display_name = "Error"
weight = 5
enable = true
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.9
objective = "Responsibility of this agent is checking errors in code"
is_custom_agent = false
is_corrective_code_enabled = false

[code_review_agent.agents.business_logic_validation]
agent_id = "9fa43db8-4a3d-43e8-95c0-de96ed58e606"
display_name = "Business Rule"
enable = true
weight = 5
custom_prompt = ""
is_override = true
exclusions = []
inclusions = []
confidence_score = 0.9
objective = "Responsibility of this agent is checking business logic validation"
is_custom_agent = false
is_corrective_code_enabled = false

[chat]
enable = true
model = "gpt-4o"
is_override = true
custom_prompt = ""

[pr_summary]
agent_id = "294c1355-38c7-4f69-8914-c95c92e16dbb"
enable = true
model = "gpt-4o"
is_override = true
custom_prompt = ""
is_custom_agent = false
